import fs from 'fs';
import path from 'path';

// カテゴリの並び順は data/sidebar-order.json で管理する。
// 「設定」ページから並び替え・カテゴリ追加をすると、このファイルが書き換わる。
function readOrder() {
  try {
    const filePath = path.join(process.cwd(), 'data', 'sidebar-order.json');
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  } catch (e) {
    return [];
  }
}

const order = readOrder();

const sidebars = {
  manualSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: '📖 マニュアル目次',
    },
    // 各カテゴリはフォルダ内のページを自動収集する(順番はページのsidebar_position、
    // ラベル・説明文はそのフォルダの_category_.jsonを使用)。
    // カテゴリ自体の並び順は、この配列(=order)の順番がそのまま使われる。
    ...order.map((folder) => ({
      type: 'autogenerated',
      dirName: folder,
    })),
  ],
};

export default sidebars;
