import fs from 'fs';
import path from 'path';

// カテゴリの並び順は data/sidebar-order.json で管理する。
// 「設定」ページから並び替え・カテゴリ追加をすると、このファイルが書き換わる。
function readOrder() {
  try {
    const filePath = path.join(process.cwd(), 'data', 'sidebar-order.json');
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  } catch (e) {
    return [];
  }
}

// カテゴリの表示名は docs/<folder>/_category_.json の label を使う。
// 「設定」ページでカテゴリ名を変更すると、このファイルが書き換わる。
function categoryLabel(folder, fallback) {
  try {
    const filePath = path.join(process.cwd(), 'docs', folder, '_category_.json');
    const data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    return data.label || fallback;
  } catch (e) {
    return fallback;
  }
}

const order = readOrder();

const sidebars = {
  manualSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: '📖 マニュアル目次',
    },
    // 各カテゴリは、見出し(category)を明示的に用意し、
    // その中身(items)だけをフォルダから自動収集する。
    // - カテゴリ名: docs/<folder>/_category_.json の label
    // - カテゴリの並び順: このorder配列の順番
    // - カテゴリ内のページの並び順: 各ページのsidebar_position
    ...order.map((folder) => ({
      type: 'category',
      label: categoryLabel(folder, folder),
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: folder }],
    })),
  ],
};

export default sidebars;
